/home/allenai/data/*.log {
    weekly
    rotate 4
    compress
    delaycompress
    missingok
    notifempty
    create 0644 allenai allenai
    dateext
    dateformat -%Y%m%d
}

/tmp/*.log {
    weekly
    rotate 2
    compress
    delaycompress
    missingok
    notifempty
    create 0644 allenai allenai
    dateext
    dateformat -%Y%m%d
}
